title="The book-server backend configuration file"

[app]
port = 3000
read_timeout = 30 #seconds
write_timeout = 30 #seconds
idle_timeout = 30 #seconds
version = "alpha-0.0.1"
debug = true
env = "development"
key = "rezoanssuperdupersecretkey"
scheme = "http"

[basic_auth_secrets]
admin = "secret()" # username = password

[redis]
db_url = "localhost"
db_port = 6379
data_expiration = 0
db_password = ""
db_prefix = "paceg_"